import type { ShoppingRecommendationResponse } from "./types"

export const affiliateMockData: ShoppingRecommendationResponse = {
  wardrobeGaps: [
    {
      id: "gap-1",
      title: "Structured neutral blazer",
      description: "A tailored blazer would multiply the number of polished looks in your wardrobe",
      category: "outerwear",
      priority: "high",
      reason:
        "You have strong casual basics but lack a structured layer that upgrades denim, trousers, and dresses",
      searchQuery: "neutral tailored blazer structured beige smart casual",
      styleTags: ["smart-casual", "tailored", "neutral", "polished"],
      colorPreferences: ["beige", "camel", "taupe"],
      occasion: "work, lunch, dinner",
    },
    {
      id: "gap-2",
      title: "Black loafers",
      description: "A clean black loafer adds polish without becoming too formal",
      category: "shoes",
      priority: "high",
      reason:
        "Your current footwear is too casual for several smart looks and too limited for office or dinner styling",
      searchQuery: "black loafers minimal leather smart wardrobe",
      styleTags: ["classic", "minimal", "smart", "versatile"],
      colorPreferences: ["black"],
      occasion: "work, dinner, city",
    },
    {
      id: "gap-3",
      title: "Slim leather belt",
      description: "A simple belt sharpens proportions and finishes tucked or tailored outfits",
      category: "accessories",
      priority: "medium",
      reason:
        "You have several outfits that would benefit from waist definition or visual structure",
      searchQuery: "slim leather belt black or tan minimal wardrobe",
      styleTags: ["minimal", "structured", "finishing-piece"],
      colorPreferences: ["black", "tan"],
      occasion: "everyday",
    },
  ],
  recommendedProducts: [
    {
      id: "prod-1",
      name: "Tailored Single-Breasted Blazer",
      brand: "ASOS DESIGN",
      merchant: "ASOS",
      price: "89.00",
      currency: "AUD",
      image:
        "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80",
      productUrl: "https://example.com/asos-blazer",
      affiliateUrl: "https://affiliate.example.com/asos-blazer",
      commissionEligible: true,
      category: "outerwear",
      styleTags: ["smart-casual", "tailored", "neutral"],
      availableSizes: ["6", "8", "10", "12", "14"],
      colors: ["beige"],
      matchedWardrobeGapId: "gap-1",
      matchedWardrobeGapTitle: "Structured neutral blazer",
      rating: 4.5,
      reviewCount: 126,
      inStock: true,
    },
    {
      id: "prod-2",
      name: "Minimal Leather Loafers",
      brand: "Amazon Essentials",
      merchant: "Amazon",
      price: "74.99",
      currency: "AUD",
      image:
        "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80",
      productUrl: "https://example.com/amazon-loafers",
      affiliateUrl: "https://affiliate.example.com/amazon-loafers",
      commissionEligible: true,
      category: "shoes",
      styleTags: ["minimal", "smart", "classic"],
      availableSizes: ["38", "39", "40", "41"],
      colors: ["black"],
      matchedWardrobeGapId: "gap-2",
      matchedWardrobeGapTitle: "Black loafers",
      rating: 4.3,
      reviewCount: 248,
      inStock: true,
    },
    {
      id: "prod-3",
      name: "Slim Classic Belt",
      brand: "SHEIN",
      merchant: "SHEIN",
      price: "12.95",
      currency: "AUD",
      image:
        "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=800&q=80",
      productUrl: "https://example.com/shein-belt",
      affiliateUrl: "https://affiliate.example.com/shein-belt",
      commissionEligible: true,
      category: "accessories",
      styleTags: ["minimal", "structured"],
      availableSizes: ["S", "M", "L"],
      colors: ["black", "tan"],
      matchedWardrobeGapId: "gap-3",
      matchedWardrobeGapTitle: "Slim leather belt",
      rating: 4.1,
      reviewCount: 89,
      inStock: true,
    },
    {
      id: "prod-4",
      name: "Straight Fit Neutral Blazer",
      brand: "Temu",
      merchant: "Temu",
      price: "31.50",
      currency: "AUD",
      image:
        "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80",
      productUrl: "https://example.com/temu-blazer",
      affiliateUrl: "https://affiliate.example.com/temu-blazer",
      commissionEligible: true,
      category: "outerwear",
      styleTags: ["neutral", "tailored", "budget"],
      availableSizes: ["S", "M", "L", "XL"],
      colors: ["camel"],
      matchedWardrobeGapId: "gap-1",
      matchedWardrobeGapTitle: "Structured neutral blazer",
      rating: 3.9,
      reviewCount: 54,
      inStock: true,
    },
  ],
}
