// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/stylist-screens/BottomNav.tsx": () => import("../components/mockups/stylist-screens/BottomNav.tsx"),
  "./components/mockups/stylist-screens/HomeScreen.tsx": () => import("../components/mockups/stylist-screens/HomeScreen.tsx"),
  "./components/mockups/stylist-screens/Preview3DScreen.tsx": () => import("../components/mockups/stylist-screens/Preview3DScreen.tsx"),
  "./components/mockups/stylist-screens/ProfileScreen.tsx": () => import("../components/mockups/stylist-screens/ProfileScreen.tsx"),
  "./components/mockups/stylist-screens/ShopScreen.tsx": () => import("../components/mockups/stylist-screens/ShopScreen.tsx"),
  "./components/mockups/stylist-screens/StylistScreen.tsx": () => import("../components/mockups/stylist-screens/StylistScreen.tsx"),
  "./components/mockups/stylist-screens/WardrobeScreen.tsx": () => import("../components/mockups/stylist-screens/WardrobeScreen.tsx")
};
